version: '3.7'

services:
  postgres:
    container_name: conf_pg
    image: postgres
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: conf_user
      POSTGRES_PASSWORD: conf_pass
      POSTGRES_DB: conf_db
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6370:6379'
    volumes:
      - ./redis_data:/bitnami/redis/data
    restart: unless-stopped

  bot:
    container_name: conf_bot
    build: .
    environment:
      TZ: "Europe/Moscow"
    env_file:
      - ./.env
    ports:
      - "5001:5000"
    restart: unless-stopped
    depends_on:
      - redis
      - postgres

  nginx:
    container_name: nginx-conf
    image: nginx:1.21-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/local:/etc/nginx/conf.d
    depends_on:
      - bot
